```json
{
  "filename": "__UIDTLS_DtlsInd.aspx",
  "found": true,
  "summary": "The file contains ASP.NET web page definitions, including user interfaces for viewing details about individuals and non-clients. It includes HTML layout, JavaScript scripts, and references to stylesheets.",
  "purpose": "Provides web page interfaces for displaying and interacting with individual and non-client details within an ASP.NET application.",
  "entities": [
    "UIDTLS_DtlsInd",
    "UIDTLS_DtlsNonClient"
  ],
  "fields": [
    "WPEventIn_Label",
    "WPEvent_Label",
    "MsgBox",
    "Hidden1",
    "Hidden2",
    "l_DtlsInd",
    "l_PID_5_PatientName",
    "PID_8_Sex",
    "PatientAKAs",
    "PID_7_DateTimeOfBirth",
    "Age",
    "PID_19_SsnNumberPatient",
    "PatientPHN",
    "Relationships",
    "b_Update",
    "b_New",
    "l_ClientDetails",
    "PID_5_PatientName_XPN_GivenName",
    "PID_5_PatientName_XPN_FamilylastName",
    "PID_5_PatientName_XPN_MiddleInitialOrName",
    "l_Name",
    "b_Add",
    "b_Transfer",
    "l_NonClientDetails",
    "NID_2_NonClientContactPerson_XPN_GivenName",
    "NID_2_NonClientContactPerson_XPN_FamilylastName",
    "NID_2_NonClientContactPerson_XPN_MiddleInitialOrName",
    "NID_1_NonClientGeneral_SLDB_Title",
    "NID_1_NonClientGeneral_SLDB_Organization",
    "NID_2_NonClientLocation_PhoneNumberHome_XTN_AreaCode",
    "NID_2_NonClientLocation_PhoneNumberHome_XTN_PhoneNumber",
    "NID_2_NonClientLocation_PhoneNumberMobile_XTN_Label"
  ],
  "actors": [],
  "workflows": [],
  "business_rules": [],
  "validations": [],
  "calculations": [],
  "conditions": [],
  "system_behavior": [],
  "dependencies": [
    "SLCase.UIDTLS_DtlsInd_Extended",
    "VCVCTL_ViewController",
    "StyleSheets/SR5000_UI_UICLCSS.css",
    "JScripts/SR5000_UI_DDRK.js",
    "JScripts/SR5000_UI_Utl.js",
    "JScripts/SR5000_UI_JSOC.js"
  ],
  "exceptions": [],
  "content_gaps": []
}
```